const { Pool } = require('pg');
const config = require('../config');

let pool = null;
let schemaReady = false;

function isConfigured() {
  return Boolean(config.get('databaseUrl'));
}

function getPool() {
  if (!isConfigured()) {
    throw new Error('DATABASE_URL is not configured');
  }

  if (!pool) {
    pool = new Pool({
      connectionString: config.get('databaseUrl'),
      ssl: config.get('databaseSsl') ? { rejectUnauthorized: false } : false,
    });
  }

  return pool;
}

async function query(text, params = []) {
  return getPool().query(text, params);
}

async function initSchema() {
  if (schemaReady) return true;

  const sql = `
    CREATE TABLE IF NOT EXISTS tasks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      execution_mode TEXT NOT NULL,
      status TEXT NOT NULL,
      priority TEXT NOT NULL,
      timeout_ms INTEGER,
      retry_count INTEGER NOT NULL DEFAULT 0,
      max_retries INTEGER,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ,
      dispatch_mode TEXT,
      run_id TEXT,
      session_link TEXT,
      run_state TEXT,
      completed_at TIMESTAMPTZ,
      finished_at TIMESTAMPTZ,
      result_summary TEXT,
      last_error TEXT,
      timed_out BOOLEAN NOT NULL DEFAULT FALSE,
      cancelled_at TIMESTAMPTZ,
      notified_at TIMESTAMPTZ,
      notified_status TEXT,
      dispatched_at TIMESTAMPTZ,
      dispatch_meta JSONB
    );

    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS dispatch_meta JSONB;

    CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
    CREATE INDEX IF NOT EXISTS idx_tasks_priority_created ON tasks(priority, created_at);
    CREATE INDEX IF NOT EXISTS idx_tasks_run_id ON tasks(run_id);

    CREATE TABLE IF NOT EXISTS notifications (
      notification_id UUID PRIMARY KEY,
      event TEXT NOT NULL,
      task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      status TEXT NOT NULL,
      run_id TEXT,
      session_link TEXT,
      result_summary TEXT,
      last_error TEXT,
      finished_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      dispatch_mode TEXT,
      emitted_at TIMESTAMPTZ NOT NULL,
      delivery JSONB NOT NULL DEFAULT '{}'::jsonb
    );

    CREATE INDEX IF NOT EXISTS idx_notifications_task_id ON notifications(task_id);
    CREATE INDEX IF NOT EXISTS idx_notifications_emitted_at ON notifications(emitted_at DESC);
  `;

  await query(sql);
  schemaReady = true;
  return true;
}

async function close() {
  if (!pool) return;
  const current = pool;
  pool = null;
  schemaReady = false;
  await current.end();
}

module.exports = {
  isConfigured,
  getPool,
  query,
  initSchema,
  close,
};
